# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
$: << File.expand_path('../../lib', __FILE__)
$: << File.expand_path('../../rolls', __FILE__)
$: << File.expand_path('../fixtures', __FILE__)

require 'yuyi'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before do
    Yuyi.stub(:say)
  end
end

class Object
  def class_var class_var, value = nil
    if value
      self.send(:class_variable_set, :"@@#{class_var}", value)
    else
      self.send(:class_variable_get, :"@@#{class_var}")
    end
  end
end

def require_all_rolls
  Dir.glob(File.join Yuyi::ROLLS_DIR, '*.rb').each do |roll|
    require File.basename(roll, '.rb')
  end
end

def stub_roll roll_class
  roll_class.any_instance.stub(:install)
end
